# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/1j23jqk017k6iijp9bp1j5a26qqkqdri-hm-session-vars.fish

# Disable fish greeting
set fish_greeting

# Starship prompt
if command -v starship >/dev/null
    starship init fish | source
end

# Zoxide
if command -v zoxide >/dev/null
    zoxide init fish | source
end

# Custom cd function that also lists directory contents
function cd
    builtin cd $argv[1]
    lsd
end

# Go environment
set -x GOPATH $HOME/go
set -x GOBIN $GOPATH/bin
set -x PATH $PATH:$GOBIN

# Add local bin to PATH
set -x PATH $HOME/.local/bin $PATH

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases
    alias cat bat
    alias find fd
    alias grep rg
    alias la 'lsd -la'
    alias ll 'lsd -l'
    alias ls lsd
    alias vi nvim
    alias vim nvim

    # Interactive shell initialisation
    /nix/store/80hwwq3k3xhmhvd2my22px2nwi0kng23-fzf-0.62.0/bin/fzf --fish | source

    /nix/store/8p5y6id6dc082rfsgznlzkyxlcqm6dvs-zoxide-0.9.8/bin/zoxide init fish | source

    if test "$TERM" != dumb
        /nix/store/k1k1zwpqn5gfgdqql1z5g18i5vzrva3n-starship-1.23.0/bin/starship init fish | source

    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/Users/yoheikugue/.local/share/fish/home-manager_generated_completions" $post
    end

end
