# tmux起動時のシェルの選択
set-option -g default-shell /usr/local/bin/fish 

# tmuxを256色表示できるようにする
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

#mouse scroll on
set -g mouse on
bind-key -T edit-mode-vi WheelUpPane send-keys -X scroll-up
bind-key -T edit-mode-vi WheelDownPane send-keys -X scroll-down

# prefixキーをC-qに変更
set -g prefix C-q

# C-bのキーバインドを解除
unbind C-b

set-option -g status-position bottom

# ステータスバーを1秒毎に描画し直す
set-option -g status-interval 1

# vimのキーバインドでペインを移動する
bind h select-pane -L                                        
bind j select-pane -D                                        
bind k select-pane -U                                        
bind l select-pane -R 

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# ペインの上下分割                                             
bind s split-window -vc "#{pane_current_path}"               
# ペインの左右分割分割                                             
bind v split-window -hc "#{pane_current_path}"  
# ウィンドウの移動
bind p previous-window
bind n next-window
# ペイン終了                                                 
bind x kill-pane                                             
# ウィンドウ終了                                             
bind X kill-window                                           

#ペインの線
set-option -g pane-border-style bg='#a89984'
set-option -g pane-border-style fg='#a89984'
set-option -g pane-active-border-style bg='#95c4ce'
set-option -g pane-active-border-style fg='#95c4ce'

source-file ~/.tmux/tmuxline.conf
set -gq status-utf8 "on"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
#run '~/.tmux/plugins/tmux-online-status/online_status.tmux'
#run '~/.tmux/plugins/tmux-battery/battery.tmux'
