# tmuxËµ∑ÂãïÊôÇ„ÅÆ„Ç∑„Çß„É´„ÅÆÈÅ∏Êäû
set-option -g default-shell /usr/local/bin/fish 

# tmux„Çí256Ëâ≤Ë°®Á§∫„Åß„Åç„Çã„Çà„ÅÜ„Å´„Åô„Çã
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

#mouse scroll on
set -g mouse on
bind-key -T edit-mode-vi WheelUpPane send-keys -X scroll-up
bind-key -T edit-mode-vi WheelDownPane send-keys -X scroll-down

# prefix„Ç≠„Éº„ÇíC-q„Å´Â§âÊõ¥
set -g prefix C-q

# C-b„ÅÆ„Ç≠„Éº„Éê„Ç§„É≥„Éâ„ÇíËß£Èô§
unbind C-b

set-option -g status-position bottom

# „Çπ„ÉÜ„Éº„Çø„Çπ„Éê„Éº„Çí1ÁßíÊØé„Å´ÊèèÁîª„ÅóÁõ¥„Åô
set-option -g status-interval 1

# vim„ÅÆ„Ç≠„Éº„Éê„Ç§„É≥„Éâ„Åß„Éö„Ç§„É≥„ÇíÁßªÂãï„Åô„Çã
bind h select-pane -L                                        
bind j select-pane -D                                        
bind k select-pane -U                                        
bind l select-pane -R 

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# „Éö„Ç§„É≥„ÅÆ‰∏ä‰∏ãÂàÜÂâ≤                                             
bind s split-window -vc "#{pane_current_path}"               
# „Éö„Ç§„É≥„ÅÆÂ∑¶Âè≥ÂàÜÂâ≤ÂàÜÂâ≤                                             
bind v split-window -hc "#{pane_current_path}"  
# „Ç¶„Ç£„É≥„Éâ„Ç¶„ÅÆÁßªÂãï
bind p previous-window
bind n next-window
# „Éö„Ç§„É≥ÁµÇ‰∫Ü                                                 
bind x kill-pane                                             
# „Ç¶„Ç£„É≥„Éâ„Ç¶ÁµÇ‰∫Ü                                             
bind X kill-window                                           

#„Éö„Ç§„É≥„ÅÆÁ∑ö
set-option -g pane-border-style bg='#a89984'
set-option -g pane-border-style fg='#a89984'
set-option -g pane-active-border-style bg='#95c4ce'
set-option -g pane-active-border-style fg='#95c4ce'

source-file ~/.tmux/tmuxline.conf
set -gq status-utf8 "on"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
#run '~/.tmux/plugins/tmux-online-status/online_status.tmux'
#run '~/.tmux/plugins/tmux-battery/battery.tmux'
